// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"
)

const getDeck = `-- name: GetDeck :one
SELECT id, name, language, translation_language, created_at, updated_at FROM decks WHERE id = ?
`

func (q *Queries) GetDeck(ctx context.Context, id string) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.TranslationLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeckNames = `-- name: ListDeckNames :many
SELECT id, name FROM decks ORDER BY name
`

type ListDeckNamesRow struct {
	ID   string `db:"id"`
	Name string `db:"name"`
}

func (q *Queries) ListDeckNames(ctx context.Context) ([]ListDeckNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeckNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeckNamesRow{}
	for rows.Next() {
		var i ListDeckNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeck = `-- name: UpsertDeck :exec
INSERT INTO decks (id, name, language, translation_language, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    language = EXCLUDED.language,
    translation_language = EXCLUDED.translation_language,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertDeckParams struct {
	ID                  string `db:"id"`
	Name                string `db:"name"`
	Language            string `db:"language"`
	TranslationLanguage string `db:"translation_language"`
}

func (q *Queries) UpsertDeck(ctx context.Context, arg UpsertDeckParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeck,
		arg.ID,
		arg.Name,
		arg.Language,
		arg.TranslationLanguage,
	)
	return err
}
