// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"
)

const getDeck = `-- name: GetDeck :one
SELECT id, name, language, translation_language, input_mappings, created_at, updated_at FROM decks WHERE id = ?
`

func (q *Queries) GetDeck(ctx context.Context, id string) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.TranslationLanguage,
		&i.InputMappings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeckEntryCount = `-- name: GetDeckEntryCount :one
SELECT CAST(COUNT(*) AS INTEGER) FROM entries WHERE deck_id = ?
`

func (q *Queries) GetDeckEntryCount(ctx context.Context, deckID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeckEntryCount, deckID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDeckNames = `-- name: ListDeckNames :many
SELECT id, name FROM decks ORDER BY name
`

type ListDeckNamesRow struct {
	ID   string `db:"id"`
	Name string `db:"name"`
}

func (q *Queries) ListDeckNames(ctx context.Context) ([]ListDeckNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeckNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeckNamesRow{}
	for rows.Next() {
		var i ListDeckNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecksWithStats = `-- name: ListDecksWithStats :many
SELECT d.id, d.name, d.language, d.translation_language,
       COUNT(e.id) AS entry_count
FROM decks d
LEFT JOIN entries e ON e.deck_id = d.id
GROUP BY d.id
ORDER BY d.name
`

type ListDecksWithStatsRow struct {
	ID                  string `db:"id"`
	Name                string `db:"name"`
	Language            string `db:"language"`
	TranslationLanguage string `db:"translation_language"`
	EntryCount          int64  `db:"entry_count"`
}

func (q *Queries) ListDecksWithStats(ctx context.Context) ([]ListDecksWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDecksWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecksWithStatsRow{}
	for rows.Next() {
		var i ListDecksWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Language,
			&i.TranslationLanguage,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeck = `-- name: UpsertDeck :exec
INSERT INTO decks (id, name, language, translation_language, input_mappings, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    language = EXCLUDED.language,
    translation_language = EXCLUDED.translation_language,
    input_mappings = EXCLUDED.input_mappings,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertDeckParams struct {
	ID                  string `db:"id"`
	Name                string `db:"name"`
	Language            string `db:"language"`
	TranslationLanguage string `db:"translation_language"`
	InputMappings       string `db:"input_mappings"`
}

func (q *Queries) UpsertDeck(ctx context.Context, arg UpsertDeckParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeck,
		arg.ID,
		arg.Name,
		arg.Language,
		arg.TranslationLanguage,
		arg.InputMappings,
	)
	return err
}
