// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
)

const deleteEntriesByDeck = `-- name: DeleteEntriesByDeck :exec
DELETE FROM entries WHERE deck_id = ?
`

func (q *Queries) DeleteEntriesByDeck(ctx context.Context, deckID string) error {
	_, err := q.db.ExecContext(ctx, deleteEntriesByDeck, deckID)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, deck_id, term, notes, position, created_at, updated_at FROM entries WHERE id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Term,
		&i.Notes,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntriesByDeck = `-- name: ListEntriesByDeck :many
SELECT id, deck_id, term, notes, position, created_at, updated_at FROM entries WHERE deck_id = ? ORDER BY position
`

func (q *Queries) ListEntriesByDeck(ctx context.Context, deckID string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Term,
			&i.Notes,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntry = `-- name: UpsertEntry :exec
INSERT INTO entries (id, deck_id, term, notes, position, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    deck_id = EXCLUDED.deck_id,
    term = EXCLUDED.term,
    notes = EXCLUDED.notes,
    position = EXCLUDED.position,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertEntryParams struct {
	ID       string `db:"id"`
	DeckID   string `db:"deck_id"`
	Term     string `db:"term"`
	Notes    string `db:"notes"`
	Position int64  `db:"position"`
}

func (q *Queries) UpsertEntry(ctx context.Context, arg UpsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntry,
		arg.ID,
		arg.DeckID,
		arg.Term,
		arg.Notes,
		arg.Position,
	)
	return err
}
