// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry_tags.sql

package db

import (
	"context"
)

const deleteEntryTag = `-- name: DeleteEntryTag :exec
DELETE FROM entry_tags WHERE entry_id = ? AND tag = ?
`

type DeleteEntryTagParams struct {
	EntryID string `db:"entry_id"`
	Tag     string `db:"tag"`
}

func (q *Queries) DeleteEntryTag(ctx context.Context, arg DeleteEntryTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntryTag, arg.EntryID, arg.Tag)
	return err
}

const deleteTagsByEntry = `-- name: DeleteTagsByEntry :exec
DELETE FROM entry_tags WHERE entry_id = ?
`

func (q *Queries) DeleteTagsByEntry(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deleteTagsByEntry, entryID)
	return err
}

const getTagsByEntry = `-- name: GetTagsByEntry :many
SELECT tag FROM entry_tags WHERE entry_id = ? ORDER BY tag
`

func (q *Queries) GetTagsByEntry(ctx context.Context, entryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEntryTag = `-- name: InsertEntryTag :exec
INSERT INTO entry_tags (entry_id, tag) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type InsertEntryTagParams struct {
	EntryID string `db:"entry_id"`
	Tag     string `db:"tag"`
}

func (q *Queries) InsertEntryTag(ctx context.Context, arg InsertEntryTagParams) error {
	_, err := q.db.ExecContext(ctx, insertEntryTag, arg.EntryID, arg.Tag)
	return err
}
