// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: examples.sql

package db

import (
	"context"
)

const deleteExamplesByEntry = `-- name: DeleteExamplesByEntry :exec
DELETE FROM examples WHERE entry_id = ?
`

func (q *Queries) DeleteExamplesByEntry(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deleteExamplesByEntry, entryID)
	return err
}

const getExamplesByEntry = `-- name: GetExamplesByEntry :many
SELECT text, translation FROM examples WHERE entry_id = ? ORDER BY position
`

type GetExamplesByEntryRow struct {
	Text        string `db:"text"`
	Translation string `db:"translation"`
}

func (q *Queries) GetExamplesByEntry(ctx context.Context, entryID string) ([]GetExamplesByEntryRow, error) {
	rows, err := q.db.QueryContext(ctx, getExamplesByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExamplesByEntryRow{}
	for rows.Next() {
		var i GetExamplesByEntryRow
		if err := rows.Scan(&i.Text, &i.Translation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertExample = `-- name: InsertExample :exec
INSERT INTO examples (entry_id, text, translation, position) VALUES (?, ?, ?, ?)
`

type InsertExampleParams struct {
	EntryID     string `db:"entry_id"`
	Text        string `db:"text"`
	Translation string `db:"translation"`
	Position    int64  `db:"position"`
}

func (q *Queries) InsertExample(ctx context.Context, arg InsertExampleParams) error {
	_, err := q.db.ExecContext(ctx, insertExample,
		arg.EntryID,
		arg.Text,
		arg.Translation,
		arg.Position,
	)
	return err
}
