// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Deck struct {
	ID                  string    `db:"id"`
	Name                string    `db:"name"`
	Language            string    `db:"language"`
	TranslationLanguage string    `db:"translation_language"`
	CreatedAt           time.Time `db:"created_at"`
	UpdatedAt           time.Time `db:"updated_at"`
}

type DeckTag struct {
	DeckID string `db:"deck_id"`
	Tag    string `db:"tag"`
}

type Entry struct {
	ID        string    `db:"id"`
	DeckID    string    `db:"deck_id"`
	Term      string    `db:"term"`
	Notes     string    `db:"notes"`
	Position  int64     `db:"position"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type EntryTag struct {
	EntryID string `db:"entry_id"`
	Tag     string `db:"tag"`
}

type Example struct {
	ID          int64  `db:"id"`
	EntryID     string `db:"entry_id"`
	Text        string `db:"text"`
	Translation string `db:"translation"`
	Position    int64  `db:"position"`
}

type Progress struct {
	DeckID    string     `db:"deck_id"`
	EntryID   string     `db:"entry_id"`
	Reverse   int64      `db:"reverse"`
	Ease      float64    `db:"ease"`
	Interval  int64      `db:"interval"`
	Due       *time.Time `db:"due"`
	Correct   int64      `db:"correct"`
	Incorrect int64      `db:"incorrect"`
}

type Review struct {
	ID         int64     `db:"id"`
	SessionID  int64     `db:"session_id"`
	DeckID     string    `db:"deck_id"`
	EntryID    string    `db:"entry_id"`
	Grade      int64     `db:"grade"`
	Reverse    int64     `db:"reverse"`
	ReviewedAt time.Time `db:"reviewed_at"`
}

type Session struct {
	ID         int64      `db:"id"`
	StartedAt  time.Time  `db:"started_at"`
	FinishedAt *time.Time `db:"finished_at"`
	Reviewed   int64      `db:"reviewed"`
	Correct    int64      `db:"correct"`
	Incorrect  int64      `db:"incorrect"`
	DurationMs int64      `db:"duration_ms"`
}

type SyncState struct {
	Path         string    `db:"path"`
	LastModified time.Time `db:"last_modified"`
	SyncedAt     time.Time `db:"synced_at"`
}

type Tag struct {
	Tag string `db:"tag"`
}

type Translation struct {
	ID       int64  `db:"id"`
	EntryID  string `db:"entry_id"`
	Text     string `db:"text"`
	Position int64  `db:"position"`
}

type TypingDetail struct {
	ReviewID      int64   `db:"review_id"`
	UserInput     string  `db:"user_input"`
	CorrectAnswer string  `db:"correct_answer"`
	Similarity    float64 `db:"similarity"`
}
