// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package db

import (
	"context"
	"time"
)

const getAllProgress = `-- name: GetAllProgress :many
SELECT deck_id, entry_id, reverse, ease, interval, due, correct, incorrect
FROM progress
`

func (q *Queries) GetAllProgress(ctx context.Context) ([]Progress, error) {
	rows, err := q.db.QueryContext(ctx, getAllProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Progress{}
	for rows.Next() {
		var i Progress
		if err := rows.Scan(
			&i.DeckID,
			&i.EntryID,
			&i.Reverse,
			&i.Ease,
			&i.Interval,
			&i.Due,
			&i.Correct,
			&i.Incorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeckProgress = `-- name: GetDeckProgress :many
SELECT entry_id,
    CAST(SUM(correct) AS INTEGER) as correct,
    CAST(SUM(incorrect) AS INTEGER) as incorrect
FROM progress
WHERE deck_id = ?
GROUP BY entry_id
`

type GetDeckProgressRow struct {
	EntryID   string `db:"entry_id"`
	Correct   int64  `db:"correct"`
	Incorrect int64  `db:"incorrect"`
}

func (q *Queries) GetDeckProgress(ctx context.Context, deckID string) ([]GetDeckProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeckProgress, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDeckProgressRow{}
	for rows.Next() {
		var i GetDeckProgressRow
		if err := rows.Scan(&i.EntryID, &i.Correct, &i.Incorrect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueCards = `-- name: GetDueCards :many
SELECT deck_id, entry_id, reverse, ease, interval, due, correct, incorrect
FROM progress
WHERE deck_id = ? AND due <= ?
ORDER BY due ASC
`

type GetDueCardsParams struct {
	DeckID string     `db:"deck_id"`
	Due    *time.Time `db:"due"`
}

func (q *Queries) GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]Progress, error) {
	rows, err := q.db.QueryContext(ctx, getDueCards, arg.DeckID, arg.Due)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Progress{}
	for rows.Next() {
		var i Progress
		if err := rows.Scan(
			&i.DeckID,
			&i.EntryID,
			&i.Reverse,
			&i.Ease,
			&i.Interval,
			&i.Due,
			&i.Correct,
			&i.Incorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgress = `-- name: GetProgress :one
SELECT deck_id, entry_id, reverse, ease, interval, due, correct, incorrect
FROM progress
WHERE deck_id = ? AND entry_id = ? AND reverse = ?
`

type GetProgressParams struct {
	DeckID  string `db:"deck_id"`
	EntryID string `db:"entry_id"`
	Reverse int64  `db:"reverse"`
}

func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (Progress, error) {
	row := q.db.QueryRowContext(ctx, getProgress, arg.DeckID, arg.EntryID, arg.Reverse)
	var i Progress
	err := row.Scan(
		&i.DeckID,
		&i.EntryID,
		&i.Reverse,
		&i.Ease,
		&i.Interval,
		&i.Due,
		&i.Correct,
		&i.Incorrect,
	)
	return i, err
}

const listNewEntriesByDeck = `-- name: ListNewEntriesByDeck :many
SELECT e.id
FROM entries e
LEFT JOIN progress p ON p.deck_id = e.deck_id AND p.entry_id = e.id
WHERE e.deck_id = ? AND p.entry_id IS NULL
ORDER BY e.position ASC
`

func (q *Queries) ListNewEntriesByDeck(ctx context.Context, deckID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNewEntriesByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO progress (deck_id, entry_id, reverse, ease, interval, due, correct, incorrect)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (deck_id, entry_id, reverse) DO UPDATE SET
    ease = excluded.ease,
    interval = excluded.interval,
    due = excluded.due,
    correct = excluded.correct,
    incorrect = excluded.incorrect
`

type UpsertProgressParams struct {
	DeckID    string     `db:"deck_id"`
	EntryID   string     `db:"entry_id"`
	Reverse   int64      `db:"reverse"`
	Ease      float64    `db:"ease"`
	Interval  int64      `db:"interval"`
	Due       *time.Time `db:"due"`
	Correct   int64      `db:"correct"`
	Incorrect int64      `db:"incorrect"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProgress,
		arg.DeckID,
		arg.EntryID,
		arg.Reverse,
		arg.Ease,
		arg.Interval,
		arg.Due,
		arg.Correct,
		arg.Incorrect,
	)
	return err
}
