// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"time"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (session_id, deck_id, entry_id, grade, reviewed_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, session_id, deck_id, entry_id, grade, reviewed_at
`

type CreateReviewParams struct {
	SessionID int64  `db:"session_id"`
	DeckID    string `db:"deck_id"`
	EntryID   string `db:"entry_id"`
	Grade     int64  `db:"grade"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.SessionID,
		arg.DeckID,
		arg.EntryID,
		arg.Grade,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DeckID,
		&i.EntryID,
		&i.Grade,
		&i.ReviewedAt,
	)
	return i, err
}

const getReviewsByEntry = `-- name: GetReviewsByEntry :many
SELECT id, session_id, deck_id, entry_id, grade, reviewed_at
FROM reviews
WHERE entry_id = ?
ORDER BY id DESC
LIMIT ?
`

type GetReviewsByEntryParams struct {
	EntryID string `db:"entry_id"`
	Limit   int64  `db:"limit"`
}

func (q *Queries) GetReviewsByEntry(ctx context.Context, arg GetReviewsByEntryParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsByEntry, arg.EntryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DeckID,
			&i.EntryID,
			&i.Grade,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewsBySession = `-- name: GetReviewsBySession :many
SELECT id, session_id, deck_id, entry_id, grade, reviewed_at
FROM reviews
WHERE session_id = ?
ORDER BY id ASC
`

func (q *Queries) GetReviewsBySession(ctx context.Context, sessionID int64) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DeckID,
			&i.EntryID,
			&i.Grade,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayStats = `-- name: GetTodayStats :one
SELECT
    CAST(COUNT(*) AS INTEGER) as total_reviews,
    CAST(IFNULL(SUM(CASE WHEN grade >= 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as correct_reviews
FROM reviews
WHERE reviewed_at >= datetime('now', 'start of day')
`

type GetTodayStatsRow struct {
	TotalReviews   int64 `db:"total_reviews"`
	CorrectReviews int64 `db:"correct_reviews"`
}

func (q *Queries) GetTodayStats(ctx context.Context) (GetTodayStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTodayStats)
	var i GetTodayStatsRow
	err := row.Scan(&i.TotalReviews, &i.CorrectReviews)
	return i, err
}

const getTodayStatsByDeck = `-- name: GetTodayStatsByDeck :one
SELECT
    CAST(COUNT(*) AS INTEGER) as total_reviews,
    CAST(IFNULL(SUM(CASE WHEN grade >= 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as correct_reviews
FROM reviews
WHERE reviewed_at >= datetime('now', 'start of day')
  AND deck_id = ?
`

type GetTodayStatsByDeckRow struct {
	TotalReviews   int64 `db:"total_reviews"`
	CorrectReviews int64 `db:"correct_reviews"`
}

func (q *Queries) GetTodayStatsByDeck(ctx context.Context, deckID string) (GetTodayStatsByDeckRow, error) {
	row := q.db.QueryRowContext(ctx, getTodayStatsByDeck, deckID)
	var i GetTodayStatsByDeckRow
	err := row.Scan(&i.TotalReviews, &i.CorrectReviews)
	return i, err
}

const getWeakTypingEntries = `-- name: GetWeakTypingEntries :many
SELECT
    r.entry_id,
    td.user_input,
    td.correct_answer,
    td.similarity,
    r.reviewed_at,
    r.grade
FROM reviews r
JOIN typing_details td ON r.id = td.review_id
WHERE r.deck_id = ? AND r.grade < 3
ORDER BY td.similarity ASC
LIMIT ?
`

type GetWeakTypingEntriesParams struct {
	DeckID string `db:"deck_id"`
	Limit  int64  `db:"limit"`
}

type GetWeakTypingEntriesRow struct {
	EntryID       string    `db:"entry_id"`
	UserInput     string    `db:"user_input"`
	CorrectAnswer string    `db:"correct_answer"`
	Similarity    float64   `db:"similarity"`
	ReviewedAt    time.Time `db:"reviewed_at"`
	Grade         int64     `db:"grade"`
}

func (q *Queries) GetWeakTypingEntries(ctx context.Context, arg GetWeakTypingEntriesParams) ([]GetWeakTypingEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeakTypingEntries, arg.DeckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeakTypingEntriesRow{}
	for rows.Next() {
		var i GetWeakTypingEntriesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.UserInput,
			&i.CorrectAnswer,
			&i.Similarity,
			&i.ReviewedAt,
			&i.Grade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
