// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (started_at)
VALUES (CURRENT_TIMESTAMP)
RETURNING id, started_at, finished_at, reviewed, correct, incorrect, duration_ms
`

func (q *Queries) CreateSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Reviewed,
		&i.Correct,
		&i.Incorrect,
		&i.DurationMs,
	)
	return i, err
}

const finishSession = `-- name: FinishSession :exec
UPDATE sessions
SET finished_at = CURRENT_TIMESTAMP,
    reviewed = ?,
    correct = ?,
    incorrect = ?,
    duration_ms = ?
WHERE id = ?
`

type FinishSessionParams struct {
	Reviewed   int64 `db:"reviewed"`
	Correct    int64 `db:"correct"`
	Incorrect  int64 `db:"incorrect"`
	DurationMs int64 `db:"duration_ms"`
	ID         int64 `db:"id"`
}

func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) error {
	_, err := q.db.ExecContext(ctx, finishSession,
		arg.Reviewed,
		arg.Correct,
		arg.Incorrect,
		arg.DurationMs,
		arg.ID,
	)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, started_at, finished_at, reviewed, correct, incorrect, duration_ms
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Reviewed,
		&i.Correct,
		&i.Incorrect,
		&i.DurationMs,
	)
	return i, err
}
