// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
	"strings"
)

const getDailyStats = `-- name: GetDailyStats :many
SELECT
    CAST(strftime('%Y-%m-%d', reviewed_at) AS TEXT) as day,
    CAST(COUNT(*) AS INTEGER) as total_reviews,
    CAST(IFNULL(SUM(CASE WHEN grade >= 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as correct_reviews
FROM reviews
GROUP BY day
ORDER BY day ASC
`

type GetDailyStatsRow struct {
	Day            string `db:"day"`
	TotalReviews   int64  `db:"total_reviews"`
	CorrectReviews int64  `db:"correct_reviews"`
}

func (q *Queries) GetDailyStats(ctx context.Context) ([]GetDailyStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyStatsRow{}
	for rows.Next() {
		var i GetDailyStatsRow
		if err := rows.Scan(&i.Day, &i.TotalReviews, &i.CorrectReviews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStatsByDecks = `-- name: GetDailyStatsByDecks :many
SELECT
    CAST(strftime('%Y-%m-%d', reviewed_at) AS TEXT) as day,
    CAST(COUNT(*) AS INTEGER) as total_reviews,
    CAST(IFNULL(SUM(CASE WHEN grade >= 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as correct_reviews
FROM reviews
WHERE deck_id IN (/*SLICE:deck_ids*/?)
GROUP BY day
ORDER BY day ASC
`

type GetDailyStatsByDecksRow struct {
	Day            string `db:"day"`
	TotalReviews   int64  `db:"total_reviews"`
	CorrectReviews int64  `db:"correct_reviews"`
}

func (q *Queries) GetDailyStatsByDecks(ctx context.Context, deckIds []string) ([]GetDailyStatsByDecksRow, error) {
	query := getDailyStatsByDecks
	var queryParams []interface{}
	if len(deckIds) > 0 {
		for _, v := range deckIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:deck_ids*/?", strings.Repeat(",?", len(deckIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:deck_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyStatsByDecksRow{}
	for rows.Next() {
		var i GetDailyStatsByDecksRow
		if err := rows.Scan(&i.Day, &i.TotalReviews, &i.CorrectReviews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryDailyStats = `-- name: GetEntryDailyStats :many
SELECT
    CAST(strftime('%Y-%m-%d', reviewed_at) AS TEXT) as day,
    CAST(COUNT(*) AS INTEGER) as total_reviews,
    CAST(IFNULL(SUM(CASE WHEN grade >= 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as correct_reviews
FROM reviews
WHERE entry_id = ?
GROUP BY day
ORDER BY day ASC
`

type GetEntryDailyStatsRow struct {
	Day            string `db:"day"`
	TotalReviews   int64  `db:"total_reviews"`
	CorrectReviews int64  `db:"correct_reviews"`
}

func (q *Queries) GetEntryDailyStats(ctx context.Context, entryID string) ([]GetEntryDailyStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntryDailyStats, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntryDailyStatsRow{}
	for rows.Next() {
		var i GetEntryDailyStatsRow
		if err := rows.Scan(&i.Day, &i.TotalReviews, &i.CorrectReviews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryReviewDays = `-- name: GetEntryReviewDays :many
SELECT DISTINCT CAST(strftime('%Y-%m-%d', reviewed_at) AS TEXT) as day
FROM reviews
WHERE entry_id = ?
ORDER BY day ASC
`

func (q *Queries) GetEntryReviewDays(ctx context.Context, entryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEntryReviewDays, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var day string
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryStats = `-- name: GetEntryStats :one
SELECT
    CAST(COUNT(*) AS INTEGER) as total_reviews,
    CAST(IFNULL(SUM(CASE WHEN strftime('%Y-%m-%d', reviewed_at) = strftime('%Y-%m-%d', 'now') THEN 1 ELSE 0 END), 0) AS INTEGER) as reviewed_today,
    CAST(IFNULL(SUM(CASE WHEN grade >= 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as correct_reviews,
    CAST(IFNULL(SUM(CASE WHEN grade < 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as incorrect_reviews,
    CAST(MAX(reviewed_at) AS TEXT) as last_reviewed
FROM reviews
WHERE entry_id = ?
`

type GetEntryStatsRow struct {
	TotalReviews     int64  `db:"total_reviews"`
	ReviewedToday    int64  `db:"reviewed_today"`
	CorrectReviews   int64  `db:"correct_reviews"`
	IncorrectReviews int64  `db:"incorrect_reviews"`
	LastReviewed     string `db:"last_reviewed"`
}

func (q *Queries) GetEntryStats(ctx context.Context, entryID string) (GetEntryStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryStats, entryID)
	var i GetEntryStatsRow
	err := row.Scan(
		&i.TotalReviews,
		&i.ReviewedToday,
		&i.CorrectReviews,
		&i.IncorrectReviews,
		&i.LastReviewed,
	)
	return i, err
}

const getReviewDays = `-- name: GetReviewDays :many
SELECT DISTINCT CAST(strftime('%Y-%m-%d', reviewed_at) AS TEXT) as day
FROM reviews
ORDER BY day ASC
`

func (q *Queries) GetReviewDays(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getReviewDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var day string
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewDaysByDecks = `-- name: GetReviewDaysByDecks :many
SELECT DISTINCT CAST(strftime('%Y-%m-%d', reviewed_at) AS TEXT) as day
FROM reviews
WHERE deck_id IN (/*SLICE:deck_ids*/?)
ORDER BY day ASC
`

func (q *Queries) GetReviewDaysByDecks(ctx context.Context, deckIds []string) ([]string, error) {
	query := getReviewDaysByDecks
	var queryParams []interface{}
	if len(deckIds) > 0 {
		for _, v := range deckIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:deck_ids*/?", strings.Repeat(",?", len(deckIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:deck_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var day string
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayStatsByDecks = `-- name: GetTodayStatsByDecks :one
SELECT
    CAST(COUNT(*) AS INTEGER) as total_reviews,
    CAST(IFNULL(SUM(CASE WHEN grade >= 3 THEN 1 ELSE 0 END), 0) AS INTEGER) as correct_reviews
FROM reviews
WHERE reviewed_at >= datetime('now', 'start of day')
  AND deck_id IN (/*SLICE:deck_ids*/?)
`

type GetTodayStatsByDecksRow struct {
	TotalReviews   int64 `db:"total_reviews"`
	CorrectReviews int64 `db:"correct_reviews"`
}

func (q *Queries) GetTodayStatsByDecks(ctx context.Context, deckIds []string) (GetTodayStatsByDecksRow, error) {
	query := getTodayStatsByDecks
	var queryParams []interface{}
	if len(deckIds) > 0 {
		for _, v := range deckIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:deck_ids*/?", strings.Repeat(",?", len(deckIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:deck_ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var i GetTodayStatsByDecksRow
	err := row.Scan(&i.TotalReviews, &i.CorrectReviews)
	return i, err
}
