// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package db

import (
	"context"
	"time"
)

const getLastModified = `-- name: GetLastModified :one
SELECT last_modified FROM sync_state WHERE path = ?
`

func (q *Queries) GetLastModified(ctx context.Context, path string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLastModified, path)
	var last_modified time.Time
	err := row.Scan(&last_modified)
	return last_modified, err
}

const upsertSyncState = `-- name: UpsertSyncState :exec
INSERT INTO sync_state (path, last_modified, synced_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (path) DO UPDATE SET
    last_modified = EXCLUDED.last_modified,
    synced_at = CURRENT_TIMESTAMP
`

type UpsertSyncStateParams struct {
	Path         string    `db:"path"`
	LastModified time.Time `db:"last_modified"`
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncState, arg.Path, arg.LastModified)
	return err
}
