// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const deleteDeckTags = `-- name: DeleteDeckTags :exec
DELETE FROM deck_tags WHERE deck_id = ?
`

func (q *Queries) DeleteDeckTags(ctx context.Context, deckID string) error {
	_, err := q.db.ExecContext(ctx, deleteDeckTags, deckID)
	return err
}

const insertDeckTag = `-- name: InsertDeckTag :exec
INSERT OR IGNORE INTO deck_tags (deck_id, tag) VALUES (?, ?)
`

type InsertDeckTagParams struct {
	DeckID string `db:"deck_id"`
	Tag    string `db:"tag"`
}

func (q *Queries) InsertDeckTag(ctx context.Context, arg InsertDeckTagParams) error {
	_, err := q.db.ExecContext(ctx, insertDeckTag, arg.DeckID, arg.Tag)
	return err
}

const insertTag = `-- name: InsertTag :exec
INSERT OR IGNORE INTO tags (tag) VALUES (?)
`

func (q *Queries) InsertTag(ctx context.Context, tag string) error {
	_, err := q.db.ExecContext(ctx, insertTag, tag)
	return err
}

const listAllTags = `-- name: ListAllTags :many
SELECT tag FROM tags ORDER BY tag
`

func (q *Queries) ListAllTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeckTags = `-- name: ListDeckTags :many
SELECT tag FROM deck_tags WHERE deck_id = ? ORDER BY tag
`

func (q *Queries) ListDeckTags(ctx context.Context, deckID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeckTags, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeckTagsByDecks = `-- name: ListDeckTagsByDecks :many
SELECT deck_id, tag FROM deck_tags
WHERE deck_id IN (/* SLICE:deck_ids*/?)
ORDER BY deck_id, tag
`

func (q *Queries) ListDeckTagsByDecks(ctx context.Context, deckID string) ([]DeckTag, error) {
	rows, err := q.db.QueryContext(ctx, listDeckTagsByDecks, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeckTag{}
	for rows.Next() {
		var i DeckTag
		if err := rows.Scan(&i.DeckID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecksByTag = `-- name: ListDecksByTag :many
SELECT deck_id FROM deck_tags WHERE tag = ? ORDER BY deck_id
`

func (q *Queries) ListDecksByTag(ctx context.Context, tag string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDecksByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var deck_id string
		if err := rows.Scan(&deck_id); err != nil {
			return nil, err
		}
		items = append(items, deck_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
