// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: translations.sql

package db

import (
	"context"
)

const deleteTranslationsByEntry = `-- name: DeleteTranslationsByEntry :exec
DELETE FROM translations WHERE entry_id = ?
`

func (q *Queries) DeleteTranslationsByEntry(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deleteTranslationsByEntry, entryID)
	return err
}

const getTranslationsByEntry = `-- name: GetTranslationsByEntry :many
SELECT text FROM translations WHERE entry_id = ? ORDER BY position
`

func (q *Queries) GetTranslationsByEntry(ctx context.Context, entryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTranslationsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var text string
		if err := rows.Scan(&text); err != nil {
			return nil, err
		}
		items = append(items, text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTranslation = `-- name: InsertTranslation :exec
INSERT INTO translations (entry_id, text, position) VALUES (?, ?, ?)
`

type InsertTranslationParams struct {
	EntryID  string `db:"entry_id"`
	Text     string `db:"text"`
	Position int64  `db:"position"`
}

func (q *Queries) InsertTranslation(ctx context.Context, arg InsertTranslationParams) error {
	_, err := q.db.ExecContext(ctx, insertTranslation, arg.EntryID, arg.Text, arg.Position)
	return err
}
