// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: typing_details.sql

package db

import (
	"context"
)

const createTypingDetail = `-- name: CreateTypingDetail :exec
INSERT INTO typing_details (review_id, user_input, correct_answer, similarity)
VALUES (?, ?, ?, ?)
`

type CreateTypingDetailParams struct {
	ReviewID      int64   `db:"review_id"`
	UserInput     string  `db:"user_input"`
	CorrectAnswer string  `db:"correct_answer"`
	Similarity    float64 `db:"similarity"`
}

func (q *Queries) CreateTypingDetail(ctx context.Context, arg CreateTypingDetailParams) error {
	_, err := q.db.ExecContext(ctx, createTypingDetail,
		arg.ReviewID,
		arg.UserInput,
		arg.CorrectAnswer,
		arg.Similarity,
	)
	return err
}

const getTypingDetailByReview = `-- name: GetTypingDetailByReview :one
SELECT review_id, user_input, correct_answer, similarity
FROM typing_details
WHERE review_id = ?
`

func (q *Queries) GetTypingDetailByReview(ctx context.Context, reviewID int64) (TypingDetail, error) {
	row := q.db.QueryRowContext(ctx, getTypingDetailByReview, reviewID)
	var i TypingDetail
	err := row.Scan(
		&i.ReviewID,
		&i.UserInput,
		&i.CorrectAnswer,
		&i.Similarity,
	)
	return i, err
}
