palette:
  blue: "39"
  green: "42"
  orange: "214"
  red: "196"
  gray: "248"
  white: "255"
  background: "0"
  selection: "27"
  border: "59"
  link: "33"
  surface: "235"
  magenta: "177"
  purple: "140"
  cyan: "117"
  yellow: "220"
